### ISSUE TITLE
GOST fails to download microsoft CVEs

### ISSUE THREAD

**Issue by SeefishJones** [vulsio/gost#149]
# What did you do? (required. The issue will be **closed** when not provided.)

gost fetch microsoft --apikey blahblahblah

# What did you expect to happen?

MS CVE data to be downloaded

# What happened instead?

Retrieval failed as the fetcher is trying to grab data for months in the future e.g Nov-2022 & Dec-2022 - these pages are blank causing the process to fail.

* Current Output
* 
Failed to fetch cve data from Microsoft. targetURL: https://api.msrc.microsoft.com/cvrf/v2.0/document/2022-Nov: HTTP error. url: https://api.msrc.microsoft.com/cvrf/v2.0/document/2022-Nov, err: %!w([]error=[])

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

gost fetch microsoft --apikey abcdefgh1234

# Configuration (**MUST** fill this out):

* Go version (`go version`):
* 
go version go1.19.2 linux/amd64

* Go environment (`go env`):

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/amadeus/.cache/go-build"
GOENV="/home/amadeus/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/amadeus/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/amadeus/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.19.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.19.2/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4246865751=/tmp/go-build -gno-record-gcc-switches"

* gost environment:

Hash :  3a15e2a

To check the commit hash of HEAD
$ gost version

gost v0.4.1 3a15e2a

or

$ cd $GOPATH/src/github.com/vulsio/gost 
$ git rev-parse --short HEAD 

* command:

**Comment by SeefishJones** [comment]
I haven't included the debug info as it is no different to the regular output.

**Comment by MaineK00n** [comment]
@SeefishJones 

Sorry for late reply.
I will work on it from now on.

**Comment by MaineK00n** [comment]
Please use the latest gost.
The latest gost can fetch as follows.
```console
$ gost fetch microsoft
```
