### ISSUE TITLE
Failed to initialize vulnerability DB . err: error in vulnsrc clone or pull: failed to pull repository: error in git pull: failed to exec: exit status 128

### ISSUE THREAD

**Issue by arrow003** [vulsio/gost#192]
$ gost fetch redhat --debug
DBUG[06-12|20:52:22] git pull
DBUG[06-12|20:52:23] From https://github.com/aquasecurity/vuln-list
 * branch                    main       -> FETCH_HEAD
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: refusing to merge unrelated histories

Failed to initialize vulnerability DB . err: error in vulnsrc clone or pull: failed to pull repository: error in git pull: failed to exec: exit status 128

**Comment by arrow003** [comment]
@MaineK00n

**Comment by MaineK00n** [comment]
@arrow003 
Delete the gost cache directory and try running `fetch redhat` again.
If you are on Unix, try deleting `$HOME/.cache/gost/vuln-list`.

**Comment by arrow003** [comment]
@MaineK00n 
Thank you very much for your reply
According to your method, the problem has been resolved
