### ISSUE TITLE
Why does git clone execution of gost take long time ?

### ISSUE THREAD

**Issue by hangingman** [vulsio/gost#197]
Hello, I got a problem on using gost.

The problem is unexpectedly long execution of git clone in gost.
I investigated it and it seems caused by git clone of `https://github.com/aquasecurity/vuln-list.git` .
vuln-list repository is very large.

https://github.com/vulsio/gost/blob/4f1c3dff45a7064603dd57606a98072dd2d0bd21/git/git.go#L27-L37
https://github.com/vulsio/gost/blob/4f1c3dff45a7064603dd57606a98072dd2d0bd21/fetcher/redhat.go#L26

So, I think it's better for gost to use `git clone --depth 1` instead of `git clone`. I think it helps execution time shorter.
I tested `git clone --depth 1 https://github.com/aquasecurity/vuln-list.git` on my PC, but it takes 10 minites.

Any other suggestion is welcome.

ref: https://github.blog/jp/2021-01-13-get-up-to-speed-with-partial-clone-and-shallow-clone/

**Comment by MaineK00n** [comment]
`gost fetch` has already adopted `--depth=1` at clone, and is working on sparse checkout and so on.
FYI: https://github.com/vulsio/gost/pull/63

**Comment by hangingman** [comment]
@MaineK00n 
Thank you for your explanation.
After checked https://github.com/vulsio/gost/pull/63 and environment, I've confirmed our using Git is less than 2.25.
I updated git , then the problem is resolved.

I think it is difficult to find the load issue is caused by git version. I would appreciate, gost command show warning if using old version git.
Anyway thank you ! I'll close this issue.
