### ISSUE TITLE
security in docker : use an application user instead of root

### ISSUE THREAD

**Issue by tokyowizard** [vulsio/gost#53]
This issue is an enhancement request. Can the image run as a non-root user?

Currently, the image runs as the `root` user.
```
$ docker run --rm -it --entrypoint=/bin/sh vuls/gost:latest
/vuls # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/vuls #
```
If the user is a non-root user, we would be able to follow best practices of running as a non-root user (e.g. [[1]](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user) [[2]](https://cloud.google.com/solutions/best-practices-for-operating-containers#avoid_running_as_root)) and add proper restrictions in [Pod Security Policies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups).

**Comment by shino** [comment]
This issue was closed because it has been inactive.
