### ISSUE TITLE
Failed to clone repository: error in git clone: failed to exec: exit status 128

### ISSUE THREAD

**Issue by OldFish66** [vulsio/gost#93]
# What did you do? (required. The issue will be **closed** when not provided.)
gost fetch redhat

# What did you expect to happen?
Insert RedHat into DB Successfully.

# What happened instead?
Failed to initialize vulnerability DB . err: error in vulnsrc clone or pull: failed to clone repository: error in git clone: failed to exec: exit status 128

Please re-run the command using ```-debug``` and provide the output below.
fatal: 无法访问 'https://github.com/aquasecurity/vuln-list.git/'：Empty reply from server

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.16 linux/amd64

* gost environment:
Hash : __dbf4931__

To check the commit hash of HEAD
$ gost version
gost v0.4.0 7ad032a

**Comment by OldFish66** [comment]
I think this patch might help.
[fetch-redhat.txt](https://github.com/vulsio/gost/files/7725493/fetch-redhat.txt)

**Comment by giladsh1** [comment]
seems like the repo name has changed..
from: https://github.com/aquasecurity/vuln-list
to: https://github.com/aquasecurity/vuln-list-update

**Comment by giladsh1** [comment]
@MaineK00n @kotakanbe Any chance you plan to support this change in the aquasecurity/vuln-list repository? Any ETA available?

**Comment by MaineK00n** [comment]
Instead of cloning the big repository vuln-list like before, I'm thinking of changing it to use the finer repository vuln-list-redhat.

**Comment by giladsh1** [comment]
Thanks for the swift reply @MaineK00n, Highly appreciated!

Please note that this change is not unique to Redhat, it was also done for [Debian](https://github.com/aquasecurity/vuln-list-update/pull/219), and it seems like more breaking changes are [underway](https://github.com/aquasecurity/vuln-list-update/pull/230).

**Comment by MaineK00n** [comment]
@giladsh1 
This PR fixed the `fetch redhat`.
`fetch ubuntu` also depends on vuln-list, but ubuntu still seems to be in vuln-list.

**Comment by MaineK00n** [comment]
> Please re-run the command using -debug and provide the output below.
fatal: 无法访问 '[https://github.com/aquasecurity/vuln-list.git/'：Empty](https://github.com/aquasecurity/vuln-list.git/'%EF%BC%9AEmpty) reply from server

By the way, the original issue is probably due to the fact that vuln-list could not be cloned in the user's network environment.
